export const mutators = {
  game_mode: [
    "Soccer",
    "Hoops",
    "Dropshot",
    "Hockey",
    "Rumble",
    "Heatseeker",
    "Gridiron",
    "Knockout",
  ],
  match_length: ["Five_Minutes", "Ten_Minutes", "Twenty_Minutes", "Unlimited"],
  max_score: [
    "Default",
    "One_Goal",
    "Three_Goals",
    "Five_Goals",
    "Seven_Goals",
    "Unlimited",
  ],
  multi_ball: ["One", "Two", "Four", "Six"],
  overtime_option: [
    "Unlimited",
    "Five_Max_First_Score",
    "Five_Max_Random_Team",
  ],
  series_length_option: [
    "Unlimited",
    "Three_Games",
    "Five_Games",
    "Seven_Games",
  ],
  game_speed_option: ["Default", "Slo_Mo", "Time_Warp"],
  ball_max_speed_option: ["Default", "Slow", "Fast", "Super_Fast"],
  ball_type_option: [
    "Default",
    "Cube",
    "Puck",
    "Basketball",
    "Beachball",
    "Anniversary",
    "Haunted",
    "Ekin",
    "SpookyCube",
  ],
  ball_weight_option: [
    "Default",
    "Light",
    "Heavy",
    "Super_Light",
    "Curve_Ball",
    "Beach_Ball_Curve",
    "Magnus_FutBall",
  ],
  ball_size_option: ["Default", "Small", "Medium", "Large", "Gigantic"],
  ball_bounciness_option: [
    "Default",
    "Low",
    "High",
    "Super_High",
    "LowishBounciness",
  ],
  boost_option: [
    "Normal_Boost",
    "Unlimited_Boost",
    "Slow_Recharge",
    "Rapid_Recharge",
    "No_Boost",
  ],
  rumble_option: [
    "No_Rumble",
    "Default",
    "Slow",
    "Civilized",
    "Destruction_Derby",
    "Spring_Loaded",
    "Spikes_Only",
    "Spike_Rush",
    "Haunted_Ball_Beam",
    "Tactical",
    "BatmanRumble",
  ],
  boost_strength_option: ["One", "OneAndAHalf", "Two", "Five", "Ten"],
  gravity_option: ["Default", "Low", "High", "Super_High", "Reverse"],
  demolish_option: [
    "Default",
    "Disabled",
    "Friendly_Fire",
    "On_Contact",
    "On_Contact_FF",
  ],
  respawn_time_option: [
    "Three_Seconds",
    "Two_Seconds",
    "One_Second",
    "Disable_Goal_Reset",
  ],
  max_time_option: ["Default", "Eleven_Minutes"],
  game_event_option: ["Default", "Haunted", "Rugby"],
  audio_option: ["Default", "Haunted"],
};
