// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBots(arg1) {
  return window['go']['main']['App']['GetBots'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function StartMatch(arg1) {
  return window['go']['main']['App']['StartMatch'](arg1);
}

export function StopMatch(arg1) {
  return window['go']['main']['App']['StopMatch'](arg1);
}
